Test validate users step

diff --git a/.github/workflows/oicd-deploy.yml b/.github/workflows/oicd-deploy.yml
--- a/.github/workflows/oicd-deploy.yml
+++ b/.github/workflows/oicd-deploy.yml
@@ -47,6 +47,12 @@ jobs:
             -H 'content-type: application/json' \
             "https://api.github.com/repos/${{ github.repository }}/collaborators?affiliation=direct")
 
+          ALLOWED_USERS=$(echo "$COLLABORATORS" | jq -r '.[] | select(.permissions.push == true) | .login')
+          if ! echo "$ALLOWED_USERS" | grep -q "${{ github.actor }}"; then
+            echo "Error: User ${{ github.actor }} does not have write access."
+            exit 1
+          fi
+
   Build_and_push_image_to_ECR:
     needs: validate_user
     if: ( github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' )
